### ISSUE TITLE
Use option `random_state` / Set seed via `srand (random_state);`

### ISSUE THREAD

**Issue by falexwolf** [DmitryUlyanov/Multicore-TSNE#11]
Hi Dmitry, 

currently, the option `random_state` is avoided and thereby every tSNE plot looks different. Would you consider setting a seed for the initialization as described above, in `random_state != None`? If you want, I can make a pull request for that.

Cheers,
  Alex

**Comment by DmitryUlyanov** [comment]
Hi, I will be happy to merge your PR! Otherwise it can take me some time until I could work on it.

**Comment by falexwolf** [comment]
Cool! I'll do that, it's gonna be quick. Btw: thanks for the nice implementation!

**Comment by falexwolf** [comment]
There you go: https://github.com/DmitryUlyanov/Multicore-TSNE/pull/12.

**Comment by DmitryUlyanov** [comment]
#12 merged
