### ISSUE TITLE
Segmentation Fault (core dumped)

### ISSUE THREAD

**Issue by Data-drone** [DmitryUlyanov/Multicore-TSNE#3]
I got a `segmentation fault (core dumped)` error.

This was at the start of the `Computing` input similarities...` step.
Any ideas how to debug?

Thanks

**Comment by DmitryUlyanov** [comment]
I had this issue, when my data was highly unnormalized, still did not try do debug why it happened. I can look into it in a month, for now, try normalizing your features to [-1,1] for example, it can help.

**Comment by DmitryUlyanov** [comment]
The code changed by a lot since the issue is opened.

**Comment by huoyubai18** [comment]
I installed the tool from pypi, and normalizd my features to [-1,1], but it still has the problem.shoud i install it from source?
