### ISSUE TITLE
Support for n_components==1, others support it. 

### ISSUE THREAD

**Issue by metaheuristic** [DmitryUlyanov/Multicore-TSNE#33]
Looks like the failure might be happening in:
Multicore-TSNE/multicore_tsne/tsne.cpp
with this function: evaluateError where it is producing nans. 

Willing to send $100USD in Bitcoin to the first person that can demonstrate a solution before I do.

**Comment by DmitryUlyanov** [comment]
Hi, did you manage to resolve it? 

If yes, please send a PR, in no -- I have some time to look at it.

**Comment by metaheuristic** [comment]
@DmitryUlyanov I have not resolved it yet, the offer still stands.

**Comment by DmitryUlyanov** [comment]
Hi, take a look at this branch. 
https://github.com/DmitryUlyanov/Multicore-TSNE/tree/1d

Now any dimensionality is supported. 

Will be merged to master soon.

**Comment by metaheuristic** [comment]
That is great! I'll benchmark it during the next day or so against sklearn
TSNE for accuracy. Once confirmed I'll send you some BTC.

**Comment by DmitryUlyanov** [comment]
Looks like will never be confirmed :)
