### ISSUE TITLE
Unable to install using Pip

### ISSUE THREAD

**Issue by deepchatterjeevns** [DmitryUlyanov/Multicore-TSNE#47]
I am unable to install using pip install .It gives  Running setup.py bdist_wheel for MulticoreTSNE ... error, CMake error at CMakeLists.txt:1 Failed to run MSBuild command.Then build failed error. I am using cmake version 3.11.0-rc4, Microsoft .Net Framework v4.0.30319.
I am getting this error:
$ pip install .
Processing c:\users\deep chatterjee\multicore-tsne
Requirement already satisfied: numpy in e:\anaconda3\lib\site-packages (from Mul                                                                                                                ticoreTSNE==0.1) (1.14.5)
Requirement already satisfied: cffi in e:\anaconda3\lib\site-packages (from Mult                                                                                                                icoreTSNE==0.1) (1.10.0)
Requirement already satisfied: pycparser in e:\anaconda3\lib\site-packages (from                                                                                                                 cffi->MulticoreTSNE==0.1) (2.18)
Building wheels for collected packages: MulticoreTSNE
  Running setup.py bdist_wheel for MulticoreTSNE: started
  Running setup.py bdist_wheel for MulticoreTSNE: finished with status 'error'
  Complete output from command E:\Anaconda3\python.exe -u -c "import setuptools,                                                                                                                 tokenize;__file__='C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-                                                                                                                req-build-fc9af9iu\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f                                                                                                                .read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" b                                                                                                                dist_wheel -d C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-wheel-c0r7vy                                                                                                                ex --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\MulticoreTSNE
  copying MulticoreTSNE\__init__.py -> build\lib.win-amd64-3.6\MulticoreTSNE
  creating build\lib.win-amd64-3.6\MulticoreTSNE\tests
  copying MulticoreTSNE\tests\test_base.py -> build\lib.win-amd64-3.6\MulticoreT                                                                                                                SNE\tests
  copying MulticoreTSNE\tests\__init__.py -> build\lib.win-amd64-3.6\MulticoreTS                                                                                                                NE\tests
  running egg_info
  creating MulticoreTSNE.egg-info
  writing MulticoreTSNE.egg-info\PKG-INFO
  writing dependency_links to MulticoreTSNE.egg-info\dependency_links.txt
  writing requirements to MulticoreTSNE.egg-info\requires.txt
  writing top-level names to MulticoreTSNE.egg-info\top_level.txt
  writing manifest file 'MulticoreTSNE.egg-info\SOURCES.txt'
  reading manifest file 'MulticoreTSNE.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'MulticoreTSNE.egg-info\SOURCES.txt'
  running build_ext
  cmake version 3.11.0-rc4

  CMake suite maintained and supported by Kitware (kitware.com/cmake).
  -- Building for: Visual Studio 10 2010
  CMake Error at CMakeLists.txt:1 (PROJECT):
    Failed to run MSBuild command:

      C:/Windows/Microsoft.NET/Framework/v4.0.30319/MSBuild.exe

    to get the value of VCTargetsPath:

      Microsoft (R) Build Engine version 4.6.1055.0
      [Microsoft .NET Framework, version 4.0.30319.42000]
      Copyright (C) Microsoft Corporation. All rights reserved.

      Build started 02-08-2018 17:04:52.
      Project "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-req-build-f                                                                                                                c9af9iu\build\temp.win-amd64-3.6\Release\CMakeFiles\3.11.0-rc4\VCTargetsPath.vcx                                                                                                                proj" on node 1 (default targets).
      C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-req-build-fc9af9iu\b                                                                                                                uild\temp.win-amd64-3.6\Release\CMakeFiles\3.11.0-rc4\VCTargetsPath.vcxproj(14,2                                                                                                                ): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not                                                                                                                 found. Confirm that the path in the <Import> declaration is correct, and that th                                                                                                                e file exists on disk.
      Done Building Project "C:\Users\Public\Documents\Wondershare\CreatorTemp\p                                                                                                                ip-req-build-fc9af9iu\build\temp.win-amd64-3.6\Release\CMakeFiles\3.11.0-rc4\VCT                                                                                                                argetsPath.vcxproj" (default targets) -- FAILED.

      Build FAILED.

      "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-req-build-fc9af9iu\                                                                                                                build\temp.win-amd64-3.6\Release\CMakeFiles\3.11.0-rc4\VCTargetsPath.vcxproj" (d                                                                                                                efault target) (1) ->
        C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-req-build-fc9af9iu                                                                                                                \build\temp.win-amd64-3.6\Release\CMakeFiles\3.11.0-rc4\VCTargetsPath.vcxproj(14                                                                                                                ,2): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was no                                                                                                                t found. Confirm that the path in the <Import> declaration is correct, and that                                                                                                                 the file exists on disk.

          0 Warning(s)
          1 Error(s)

      Time Elapsed 00:00:00.06

    Exit code: 1

  -- Configuring incomplete, errors occurred!
  See also "C:/Users/Public/Documents/Wondershare/CreatorTemp/pip-req-build-fc9a                                                                                                                f9iu/build/temp.win-amd64-3.6/Release/CMakeFiles/CMakeOutput.log".

  ERROR: Cannot generate Makefile. See above errors.

  ----------------------------------------
  Failed building wheel for MulticoreTSNE
  Running setup.py clean for MulticoreTSNE
Failed to build MulticoreTSNE
Installing collected packages: MulticoreTSNE
  Running setup.py install for MulticoreTSNE: started
    Running setup.py install for MulticoreTSNE: finished with status 'error'
    Complete output from command E:\Anaconda3\python.exe -u -c "import setuptool                                                                                                                s, tokenize;__file__='C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pi                                                                                                                p-req-build-fc9af9iu\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code                                                                                                                =f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))"                                                                                                                 install --record C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-record-r                                                                                                                ni883bh\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\MulticoreTSNE
    copying MulticoreTSNE\__init__.py -> build\lib.win-amd64-3.6\MulticoreTSNE
    creating build\lib.win-amd64-3.6\MulticoreTSNE\tests
    copying MulticoreTSNE\tests\test_base.py -> build\lib.win-amd64-3.6\Multicor                                                                                                                eTSNE\tests
    copying MulticoreTSNE\tests\__init__.py -> build\lib.win-amd64-3.6\Multicore                                                                                                                TSNE\tests
    running egg_info
    writing MulticoreTSNE.egg-info\PKG-INFO
    writing dependency_links to MulticoreTSNE.egg-info\dependency_links.txt
    writing requirements to MulticoreTSNE.egg-info\requires.txt
    writing top-level names to MulticoreTSNE.egg-info\top_level.txt
    reading manifest file 'MulticoreTSNE.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'MulticoreTSNE.egg-info\SOURCES.txt'
    running build_ext
    cmake version 3.11.0-rc4

    CMake suite maintained and supported by Kitware (kitware.com/cmake).
    -- Building for: Visual Studio 10 2010
    CMake Error at CMakeLists.txt:1 (PROJECT):
      Failed to run MSBuild command:

        C:/Windows/Microsoft.NET/Framework/v4.0.30319/MSBuild.exe

      to get the value of VCTargetsPath:

        Microsoft (R) Build Engine version 4.6.1055.0
        [Microsoft .NET Framework, version 4.0.30319.42000]
        Copyright (C) Microsoft Corporation. All rights reserved.

        Build started 02-08-2018 17:04:57.
        Project "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-req-build                                                                                                                -fc9af9iu\build\temp.win-amd64-3.6\Release\CMakeFiles\3.11.0-rc4\VCTargetsPath.v                                                                                                                cxproj" on node 1 (default targets).
        C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-req-build-fc9af9iu                                                                                                                \build\temp.win-amd64-3.6\Release\CMakeFiles\3.11.0-rc4\VCTargetsPath.vcxproj(14                                                                                                                ,2): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was no                                                                                                                t found. Confirm that the path in the <Import> declaration is correct, and that                                                                                                                 the file exists on disk.
        Done Building Project "C:\Users\Public\Documents\Wondershare\CreatorTemp                                                                                                                \pip-req-build-fc9af9iu\build\temp.win-amd64-3.6\Release\CMakeFiles\3.11.0-rc4\V                                                                                                                CTargetsPath.vcxproj" (default targets) -- FAILED.

        Build FAILED.

        "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-req-build-fc9af9i                                                                                                                u\build\temp.win-amd64-3.6\Release\CMakeFiles\3.11.0-rc4\VCTargetsPath.vcxproj"                                                                                                                 (default target) (1) ->
          C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-req-build-fc9af9                                                                                                                iu\build\temp.win-amd64-3.6\Release\CMakeFiles\3.11.0-rc4\VCTargetsPath.vcxproj(                                                                                                                14,2): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was                                                                                                                 not found. Confirm that the path in the <Import> declaration is correct, and tha                                                                                                                t the file exists on disk.

            0 Warning(s)
            1 Error(s)

        Time Elapsed 00:00:00.04

      Exit code: 1

    -- Configuring incomplete, errors occurred!
    See also "C:/Users/Public/Documents/Wondershare/CreatorTemp/pip-req-build-fc                                                                                                                9af9iu/build/temp.win-amd64-3.6/Release/CMakeFiles/CMakeOutput.log".

    ERROR: Cannot generate Makefile. See above errors.

    ----------------------------------------
Command "E:\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:                                                                                                                \\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-req-build-fc9af9iu\\se                                                                                                                tup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n'                                                                                                                , '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Use                                                                                                                rs\Public\Documents\Wondershare\CreatorTemp\pip-record-rni883bh\install-record.t                                                                                                                xt --single-version-externally-managed --compile" failed with error code 1 in C:                                                                                                                \Users\Public\Documents\Wondershare\CreatorTemp\pip-req-build-fc9af9iu\

Thanks in advance

**Comment by ccheung39** [comment]
I have the same problem and unable to install

**Comment by koalap-2018** [comment]
me too. i tried eveything and nothing seemed to work :(

**Comment by AmichayAfriat** [comment]
Same here, Windows, py 3.7.4

**Comment by deepchatterjeevns** [comment]
I have successfully installed it today on my Windows 8.1 machine. Steps worked for me:
1. Uninstall and re-install cmake link:https://cmake.org/download/
2. Install Chocolatey link: https://chocolatey.org/courses/installation/installing?method=installing-chocolatey?quiz=true
3. Install Visual c++ build tools link: https://chocolatey.org/packages/visualcpp-build-tools.
4.run pip install MulticoreTSNE at my Anaconda environment.
@ccheung39 @koalap-2018 @AmichayAfriat Hope these steps help you too. Happy Learning.

**Comment by sruthi-hub** [comment]
> I have successfully installed it today on my Windows 8.1 machine. Steps worked for me:
> 
> 1. Uninstall and re-install cmake link:https://cmake.org/download/
> 2. Install Chocolatey link: https://chocolatey.org/courses/installation/installing?method=installing-chocolatey?quiz=true
> 3. Install Visual c++ build tools link: https://chocolatey.org/packages/visualcpp-build-tools.
> 4. Run pip install MulticoreTSNE at my Anaconda environment.
> 
> @ccheung39 @koalap-2018 @AmichayAfriat Hope these steps help you too. Happy Learning.

I had the same error and followed the steps above, but I seem to get the same error again. 
I am using: python 3.7.0, Windows.
