### ISSUE TITLE
Support for embedding in D>2

### ISSUE THREAD

**Issue by matteosal** [DmitryUlyanov/Multicore-TSNE#5]
The algorithm does not seem to work properly if the target space is bigger than 2-dimensional. Is there a plan for extended functionality?

**Comment by DmitryUlyanov** [comment]
Some day I will give it a try

**Comment by sg-s** [comment]
is that even the point of t-SNE?

**Comment by matteosal** [comment]
It's mainly used for 2D visualization, so not really. 
But the real point of t-SNE is to tackle the crowding problem of "heavy" dimensionality reduction (target dimension << starting dimension), which is not tied to D=2 in any way. Hence applying the algorithm for D > 2 is perfectly meaningful and maybe could be of some use to someone.

**Comment by captify-acherednychenko** [comment]
Hey there. Agree, would be great to have n>2 support. 

@DmitryUlyanov , If I'd just change hardcoded do_dim and other vars from 2 to say 5 everywhere, will that work?

Thanks.

**Comment by DmitryUlyanov** [comment]
No, it will not. This code uses quadTree data structure which can't be used with dim > 2.

**Comment by captify-acherednychenko** [comment]
Dmitry, thanks for replying

**Comment by DmitryUlyanov** [comment]
Supported via #35
