### ISSUE TITLE
Possible to install through Pip?

### ISSUE THREAD

**Issue by steelbrain** [DmitryUlyanov/Multicore-TSNE#6]
Hi, is it possible to install this module through pip? It would greatly reduce the inertia for new users

**Comment by sg-s** [comment]
yes, as it says in the readme:

pip install -r requirements.txt

**Comment by DmitryUlyanov** [comment]
Hello, it is not possible right now, because I faced some issues I can't overcome (still waiting for someone who will help me with it)

Note, that
```
pip install -r requirements.txt
```
installs dependencies only.

**Comment by WouterVH** [comment]
what is the problem?

**Comment by steelbrain** [comment]
Fixed by https://github.com/DmitryUlyanov/Multicore-TSNE/pull/10
