### ISSUE TITLE
License Clarification

### ISSUE THREAD

**Issue by ankane** [DmitryUlyanov/Multicore-TSNE#75]
Hi @DmitryUlyanov, thanks for this library. I was looking at the license and it looks like the copyright year and name aren't filled out.

https://github.com/DmitryUlyanov/Multicore-TSNE/blob/11b0cd7df072ae6ba76c7d92d2530142cf1c4304/LICENSE.txt#L3

In the source code, there are a few headers that mention:

```txt
 *  Created by Laurens van der Maaten.
 *  Copyright 2012, Delft University of Technology. All rights reserved.
 *
 *  Multicore version by Dmitry Ulyanov, 2016. dmitry.ulyanov.msu@gmail.com
```

Also, readme mentions the license is inherited from [bhtsne](https://github.com/lvdmaaten/bhtsne), but that repo uses original BSD license (4 clause) and this one uses BSD 3 Clause.

Can you provide some clarification on the licensing?

**Comment by milianw** [comment]
As-is this repo seems to be infringing on the upstream repo as it's not keeping the original license file, nor the required copyright attribution line. @DmitryUlyanov - can you please fix that? Should be a quick matter of copying over the original license file from upstream and then adding your copyright line in addition to that of @lvdmaaten
