### ISSUE TITLE
Fix compiling

### ISSUE THREAD

**Issue by domergal16** [DmitryUlyanov/Multicore-TSNE#91]
I had trouble getting this package to  install, and have realized that if line 55 in setup.py is changed from:
`                         self.cmake_args or "--",`
to
`                         self.cmake_args or "-S",`

then multicore-TSNE compiles correctly. If this change could be made, that'd be awesome!

**Comment by 6884** [comment]
THANK YOU!!! this solved my issue as well!

**Comment by r614** [comment]
@DmitryUlyanov thoughts on merging the fix above? PyPi installations are broken with the latest cmake, and downgrading for this library conflicts with other up-to date dependencies.

**Comment by JackingChen** [comment]
this also solved my issue!

**Comment by kulibour** [comment]
THANK YOU!!! 
It works!
My error: RuntimeError: Cannot find/open tsne_multicore shared library.
