### ISSUE TITLE
Static library is built but runtime is trying to load dynamic one

### ISSUE THREAD

**Issue by tolgaeren** [DmitryUlyanov/Multicore-TSNE#98]
Hi guys,

I saw on the release notes about switching to a dynamic library. and it builds `libtsne_multicore.a` successfully, however the `__init__` is trying to load the dynamic library [here](https://github.com/DmitryUlyanov/Multicore-TSNE/blob/eee533ae2c455c1d4c28da3172d439cce45144c2/MulticoreTSNE/__init__.py#L99)

Am I missing sth or does the init file need an update?
I've tested on a Mac.

**Comment by DmitryUlyanov** [comment]
Fixed in main, thanks for reporting.
